name: "Azure Blob Storage File Upload"
description: "Uploads asset to Azure Blob Storage"
inputs:
  connection_string:
    description: "The connection string for the storage account. Used if value is set. Either connection_string or sas_token must be supplied"
    required: false
  sas_token:
    description: "The shared access signature token for the storage account. Either connection_string or sas_token must be supplied"
    required: false
  account_name:
    description: "The name of the storage account. Required if sas_token is used"
    required: false
  container_names:
    description: "The one or more space separated storage account container names corresponding to the files you want to upload"
    required: true
  source_files:
    description: "The one or more space separated filepaths to the files you want to upload"
    required: true
  overwrite:
    description: "Overwrite existing file in the destination container. Defaults to false"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
