name: Test upload To Azure Blob Storage and Structurizr Cloud push

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  upload:
    name: Upload core.dsl to Blob Storage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/blob-storage-upload
        with:
          source_file: dsl/bic/core.dsl
          container_name: test-container
          connection_string: ${{ secrets.CONNECTION_STRING }} # this value is rotated every 365 days (last rotated date YYYY-MM-DD)
          overwrite: 'true'

  push:
    name: Push Workspace to Structurizr Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aidmax/structurizr-cli-action@v1
        with:
          id: ${{ secrets.STRUCTURIZR_WORKSPACE_ID }}
          key: ${{ secrets.STRUCTURIZR_API_KEY }}
          secret: ${{ secrets.STRUCTURIZR_API_SECRET }}
          workspace: dsl/bic/workspace.dsl

